-- auto-generated definition
create table submissions
(
    unique_id                   text primary key,
    allow_live_comments         boolean,
    archived                    boolean,
    author                      text,
    author_flair_type           text,
    author_fullname             text,
    author_patreon_flair        boolean,
    author_premium              boolean,
    can_gild                    boolean,
    can_mod_post                boolean,
    clear_vote                  text,
    clicked                     boolean,
    comment_limit               double precision,
    comment_sort                text,
    comments                    text,
    contest_mode                boolean,
    created                     double precision,
    created_utc                 double precision,
    crosspost                   text,
    delete                      text,
    disable_inbox_replies       text,
    domain                      text,
    downs                       double precision,
    downvote                    text,
    duplicates                  text,
    edit                        text,
    edited                      boolean,
    enable_inbox_replies        text,
    flair                       text,
    fullname                    text,
    gild                        text,
    gilded                      double precision,
    hidden                      boolean,
    hide                        text,
    hide_score                  boolean,
    id                          text,
    id_from_url                 text,
    is_crosspostable            boolean,
    is_meta                     boolean,
    is_original_content         boolean,
    is_reddit_media_domain      boolean,
    is_robot_indexable          boolean,
    is_self                     boolean,
    is_video                    boolean,
    link_flair_background_color text,
    link_flair_text_color       text,
    link_flair_type             text,
    locked                      boolean,
    mark_visited                text,
    media_only                  boolean,
    mod                         text,
    name                        text,
    no_follow                   boolean,
    num_comments                double precision,
    num_crossposts              double precision,
    over_18                     boolean,
    parent_whitelist_status     text,
    parse                       text,
    permalink                   text,
    pinned                      boolean,
    pwls                        double precision,
    quarantine                  boolean,
    reply                       text,
    report                      text,
    save                        text,
    saved                       boolean,
    score                       double precision,
    selftext                    text,
    send_replies                boolean,
    shortlink                   text,
    spoiler                     boolean,
    stickied                    boolean,
    "STR_FIELD"                 text,
    subreddit                   text,
    subreddit_id                text,
    subreddit_name_prefixed     text,
    subreddit_subscribers       double precision,
    subreddit_type              text,
    thumbnail                   text,
    title                       text,
    total_awards_received       double precision,
    unhide                      text,
    unsave                      text,
    ups                         double precision,
    upvote                      text,
    upvote_ratio                double precision,
    url                         text,
    visited                     boolean,
    whitelist_status            text,
    wls                         double precision,
    link_flair_css_class        text,
    link_flair_richtext         text,
    link_flair_text             text,
    media                       text,
    media_embed                 text,
    secure_media                text,
    secure_media_embed          text,
    thumbnail_height            text,
    thumbnail_width             text
);

alter table submissions
    owner to unicorn_user;

